name: zenroom
on:
  push:
    branches:
      - android
  pull_request:
    branches:
      - android

jobs:
  android-build:
    name: 📱 Android build
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Android NDK build
        id: install-ndk
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r25c
          local-cache: true
          add-to-path: true
      - run: |
          find ${{ steps.install-ndk.outputs.ndk-path }}
      - run: |
          bash build/build-android.sh ${{ steps.install-ndk.outputs.ndk-path }}

