name: zenroom
on:
  push:
    paths-ignore:
      - 'docs/**'
      - 'examples/**'
      - '*.md'
    branches:
      - master
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'examples/**'
      - '*.md'
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  android-build:
    name: 📱 Android build
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Android NDK build
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r25c
          local-cache: true
      - run: |
          bash build/build-android.sh

